content:
  root_types:
    - path: People
      type: person
    - path: Books
      type: book
    - path: Games
      type: game
    - path: Movies
      type: movie
    - path: Companies
      type: company
  type: object
  properties:
    name:
      description: Name of the file, used in the breadcrumbs
      type: string
    title:
      description: Override for the name, used as page title, fallback to Name
      type: string
    subtitle:
      type: string
    # year:
    #   type: int
    description:
      type: string
    cover_artist:
      type: person
      label: Cover artist
    designer:
      type: person
    based_on:
      type: references
    series:
      type: string
      meta: series
    previous:
      description: Peference to previous in the series
      type: reference
      meta: previous

    # for people
    dob:
      title: Born
      description: Date of birth
      type: string
      column: true
    dod:
      title: Died
      description: Date of death
      type: string
      column: true
      column_always_show: true
    contact:
      type: string

    # for companies
    parent:
      type: string
    founded:
      type: string
    founders:
      type: references

    # general external links
    website:
      type: string
    websites:
      type: array
      items:
        type: string
    wikipedia:
      type: string
    goodreads:
      type: string
    bookshop:
      type: string
    anime_news_network:
      type: company
    twitch:
      type: string
    youtube:
      type: string
    vimeo:
      type: string
    imdb:
      type: string
    tmdb:
      type: string
    tpdb:
      type: string
    steam:
      type: string
    netflix:
      type: string
    spotify:
      type: string
    soundcloud:
      type: string
    hulu:
      type: string
    max:
      type: string
    adult_swim:
      type: string
      description: Adult Swim
    app_store:
      type: string
    fandom:
      type: string
    rotten_tomatoes:
      type: string
    metacritic:
      type: string
    opencritic:
      type: string
    twitter:
      type: string
    mastodon:
      type: string
    reddit:
      type: string
    facebook:
      type: string
    instagram:
      type: string
    threads:
      type: string
    linkedin:
      type: string
    tiktok:
      type: string
    telegram_channel:
      type: string
    playstation:
      type: string
    xbox:
      type: string
    gog:
      type: string
    x:
      type: string
    discord:
      type: string
    epic:
      type: string
    ign:
      type: string
    amazon:
      type: string
    prime_video:
      type: string
    apple_tv:
      type: string
    apple_podcasts:
      type: string
    apple_books:
      type: string
    peacock:
      type: string
    google_play:
      type: string
    disney_plus:
      type: string
    microsoft_store:
      type: string
    nintendo:
      type: string
    humble_bundle:
      type: string
    row8:
      type: string
    redbox:
      type: string
    vudu:
      type: string
    darkhorse:
      type: string

    # for books
    isbn:
      type: string
    isbn10:
      type: string
    isbn13:
      type: string
    oclc:
      type: string
    publishers:
      type: references
      column: true
    publication:
      description: Date or year of publication
      type: string

    # for comics
    artists:
      type: references
    colorist:
      type: person
    illustrators:
      type: references
    imprint:
      type: string
    upc:
      type: string

    # for movies, games, series, ...
    genres:
      type: array
      items:
        type: string
    length:
      type: duration
      column: true
    directors:
      type: array
      items:
        type: person
      column: true
      label: Director
    writers:
      type: references
      column: true
    distributors:
      type: references
      column: true
    rating:
      type: string
      column: true
    released:
      type: string
      column: true
    network:
      type: company
      column: true
    engine:
      type: string
    creators:
      type: array
      items:
        type: person
      column: true
      label: Creator
    authors:
      type: array
      items:
        type: person
      column: true
      label: Author
    developers:
      type: array
      items:
        type: person
      column: true
      label: Developer
    trailer:
      type: string
    editors:
      type: array
      items:
        type: person
      label: Editor
    cinematography:
      type: array
      items:
        type: person
    producers:
      type: array
      items:
        type: person
      label: Producer
    screenplay:
      type: array
      items:
        type: person
      column: true
    story_by:
      type: array
      items:
        type: person
      column: true
      label: Story
    dialogues_by:
      type: array
      items:
        type: person
      column: true
      label: Dialogues
    music:
      type: array
      items:
        type: person
    production:
      type: array
      items:
        type: company
    composers:
      type: array
      items:
        type: person
      label: Composer
    programmers:
      type: array
      items:
        type: person
      label: Programmer
    designers:
      type: array
      items:
        type: person
      label: Designer

    # for podcasts
    hosts:
      type: array
      items:
        type: person
      column: true
      label: Host
    guests:
      type: array
      items:
        type: person
      label: Guest

    remake_of:
      type: reference
      label: Remake

    characters:
      type: array
      items:
        type: character

    # for awards
    categories:
      type: array
      items:
        type: category
    
    references:
      type: array
      items:
        type: reference

    episodes:
      type: array
      items:
        type: episode

    # fields populated by the generator
    # Image                *Media  `yaml:"-" json:",omitempty"`
    # Awards               []Award `yaml:"-" json:",omitempty"`
    # EditorsAwards        []Award `yaml:"-" json:",omitempty"`
    # WritersAwards        []Award `yaml:"-" json:",omitempty"`
    # DirectorsAwards      []Award `yaml:"-" json:",omitempty"`
    # CinematographyAwards []Award `yaml:"-" json:",omitempty"`
    # MusicAwards          []Award `yaml:"-" json:",omitempty"`
    # ScreenplayAwards     []Award `yaml:"-" json:",omitempty"`
episode:
  type: object
  properties:
    name:
      type: string
    description:
      type: string
    length:
      type: duration
    released:
      type: string
    directors:
      type: array
      items:
        type: person
      label: Director
    writers:
      type: array
      items:
        type: person
      label: Writer
    editors:
      type: array
      items:
        type: person
      label: Editor
    cinematography:
      type: array
      items:
        type: person
      label: Cinematography
    teleplay:
      type: array
      items:
        type: person
      label: Teleplay
    story:
      type: array
      items:
        type: person
      label: Story
    studio:
      type: company
    characters:
      type: array
      items:
        type: character
    imdb:
      type: string
    tmdb:
      type: string
    netflix:
      type: string
    wikipedia:
      type: string
    fandom:
      type: string
# character:
#   type: object
# category:
#   type: object
