name: main

on:
  push:
    branches:
      - main
    paths-ignore:
      - _finder/**
      - .github/workflows/finder.yml
  workflow_dispatch:
    inputs:
      force:
        description: 'Path to media to index, e.g. "Movies/John Wick.yml". Leave empty for normal operation. Set to "all" to re-index all media. Can be comma-separated list.'
        required: false
        default: ""
  repository_dispatch:
    types: [deploy]

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Clone info
        uses: actions/checkout@v4
        with:
          repository: alsosee/info
          path: info
          token: ${{ secrets.PKG_TOKEN }}

      - name: Clone info state
        uses: actions/checkout@v4
        with:
          repository: alsosee/info
          path: state
          ref: state
          token: ${{ secrets.PKG_TOKEN }}

      - name: Clone media
        uses: actions/checkout@v4
        with:
          repository: alsosee/media
          path: media
          token: ${{ secrets.PKG_TOKEN }}

      - name: Set environment variable (repository_dispatch)
        if: github.event_name == 'repository_dispatch' && github.event.client_payload.force
        uses: alsosee/envset@v1
        with:
          name: FORCE
          value: ${{ github.event.client_payload.force }}

      - name: Set environment variable (workflow_dispatch)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.force
        uses: alsosee/envset@v1
        with:
          name: FORCE
          value: ${{ github.event.inputs.force }}

      - name: Run action
        uses: ./info/_finder
        with:
          info: ./info
          media: ./media
          output: ./output
          media_host: https://media.alsosee.info
          search_host: https://search.alsosee.info
          search_api_key: ${{ secrets.MEILISEARCH_KEY }}
          search_index: info
          search_master_key: ${{ secrets.MEILISEARCH_MASTER_KEY }}
          search_state: ./state/state
          ignorefile: .ignore
          force: ${{ env.FORCE }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3.5.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy output --project-name=finder --branch=main --commit-dirty=true

      - name: Commit and push state
        shell: bash
        run: |
          cd state
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes to commit"
            exit 0
          fi

          git config --global user.name 'GitHub Actions'
          git config --global user.email 'gha@alsosee.info'
          git add "state"
          git commit -m "Update index state [skip ci]"
          git push origin state
