name: American Prometheus
subtitle: The Triumph and Tragedy of J. Robert Oppenheimer
description: >
  Biography of J. Robert Oppenheimer, the physicist who led the Manhattan Project, the World War II effort to develop the first nuclear weapons, and the first director of the Institute for Advanced Study in Princeton, New Jersey.
  The book covers Oppenheimer's life from his childhood to his death in 1967.
wikipedia: https://en.wikipedia.org/wiki/American_Prometheus
amazon: https://www.amazon.com/American-Prometheus-Triumph-Tragedy-Oppenheimer/dp/0375726268
goodreads: https://www.goodreads.com/book/show/80571.American_Prometheus
authors:
  - Kai Bird
  - Martin J. Sherwin
publication: 2005-04-05
isbn: 978-0-375-72626-2
oclc: 249029647
